install:
	cp -vf higgslog /etc/logrotate.d
	cp -vf restart_servants.conf /etc/acpi/events
	cp -vf restart_servants.sh /etc/acpi/actions
	cp -vf servants /usr/local/bin
	cp -vf servants.init /etc/init.d

