TrajectoryPlannerROS:
    # Robot Configuration Parameters
    acc_lim_x: 0.8
    acc_lim_y: 0.0
    acc_lim_th: 2.0
    max_vel_x: 0.25
    min_vel_x: 0.05
    max_rotational_vel: 0.4
    min_in_place_rotational_vel: 0.1
    
    #The velocity the robot will command when trying to escape from a stuck situation    
    escape_vel: -0.05  
    
    holonomic_robot: false
    heading_scoring: false

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.05

    # Forward Simulation Parameters
    sim_time: 1.7
    sim_granularity: 0.025
    vx_samples: 3
    vtheta_samples: 20

    # Trajectory Scoring Parameters
    goal_distance_bias: 0.6
    path_distance_bias: 0.6
    occdist_scale: 0.01
    heading_lookahead: 0.325
    
    #We'll use the Dynamic Window Approach to control instead of Trajectory Rollout for this example  
    dwa: true

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.1

  
    #Eat up the plan as the robot moves along it
    prune_plan: true