/* This file was autogenerated as a part of the avr_bridge pkg
 * avr_bridge was written by Adam Stambler and Phillip Quiza of
 * Rutgers University.
 */
char getTopicTag(char const* topic) {
	if (!strcmp(topic, "compass"))
		return 0;
	return 0;
} /* getTopicTag */
