(cl:defpackage higgs_arduino_java-srv
  (:use )
  (:export
   "TESTTWOINTS"
   "<TESTTWOINTS-REQUEST>"
   "TESTTWOINTS-REQUEST"
   "<TESTTWOINTS-RESPONSE>"
   "TESTTWOINTS-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
  ))

