(cl:defpackage higgs_navigation-msg
  (:use )
  (:export
   "<ODOMDRIVERACTIONRESULT>"
   "ODOMDRIVERACTIONRESULT"
   "<ODOMDRIVERRESULT>"
   "ODOMDRIVERRESULT"
   "<ODOMDRIVERACTIONFEEDBACK>"
   "ODOMDRIVERACTIONFEEDBACK"
   "<ODOMDRIVERGOAL>"
   "ODOMDRIVERGOAL"
   "<ODOMDRIVERFEEDBACK>"
   "ODOMDRIVERFEEDBACK"
   "<ODOMDRIVERACTIONGOAL>"
   "ODOMDRIVERACTIONGOAL"
   "<ODOMDRIVERACTION>"
   "ODOMDRIVERACTION"
  ))

