(cl:in-package higgs_arduino_java-msg)
(cl:export '(BYTE_-VAL
          BYTE_
          CHAR_-VAL
          CHAR_
          UINT8_-VAL
          UINT8_
          INT8_-VAL
          INT8_
          UINT16_-VAL
          UINT16_
          INT16_-VAL
          INT16_
          UINT32_-VAL
          UINT32_
          INT32_-VAL
          INT32_
          UINT64_-VAL
          UINT64_
          INT64_-VAL
          INT64_
          FLOAT32_-VAL
          FLOAT32_
          FLOAT64_-VAL
          FLOAT64_
          STRING_-VAL
          STRING_
          TIME_-VAL
          TIME_
          DURATION_-VAL
          DURATION_
          BYTE_V-VAL
          BYTE_V
          BYTE_F-VAL
          BYTE_F
          FLOAT64_V-VAL
          FLOAT64_V
          FLOAT64_F-VAL
          FLOAT64_F
          STRING_V-VAL
          STRING_V
          STRING_F-VAL
          STRING_F
          TIME_V-VAL
          TIME_V
          TIME_F-VAL
          TIME_F
          BYTE_-VAL
          BYTE_
          BYTE_V-VAL
          BYTE_V
          BYTEMULTIARRAY_-VAL
          BYTEMULTIARRAY_
          BYTEMULTIARRAY_V-VAL
          BYTEMULTIARRAY_V
))