; Auto-generated. Do not edit!


(cl:in-package higgs_navigation-msg)


;//! \htmlinclude OdomDriverResult.msg.html

(cl:defclass <OdomDriverResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass OdomDriverResult (<OdomDriverResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OdomDriverResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OdomDriverResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name higgs_navigation-msg:<OdomDriverResult> is deprecated: use higgs_navigation-msg:OdomDriverResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OdomDriverResult>) ostream)
  "Serializes a message object of type '<OdomDriverResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OdomDriverResult>) istream)
  "Deserializes a message object of type '<OdomDriverResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OdomDriverResult>)))
  "Returns string type for a message object of type '<OdomDriverResult>"
  "higgs_navigation/OdomDriverResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OdomDriverResult)))
  "Returns string type for a message object of type 'OdomDriverResult"
  "higgs_navigation/OdomDriverResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OdomDriverResult>)))
  "Returns md5sum for a message object of type '<OdomDriverResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OdomDriverResult)))
  "Returns md5sum for a message object of type 'OdomDriverResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OdomDriverResult>)))
  "Returns full string definition for message of type '<OdomDriverResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OdomDriverResult)))
  "Returns full string definition for message of type 'OdomDriverResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# no feedback~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OdomDriverResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OdomDriverResult>))
  "Converts a ROS message object to a list"
  (cl:list 'OdomDriverResult
))
