/* Auto-generated by genmsg_cpp for file /usr/local/ros_aslab/higgs_ros/higgs_navigation/msg/OdomDriverFeedback.msg */
#ifndef HIGGS_NAVIGATION_MESSAGE_ODOMDRIVERFEEDBACK_H
#define HIGGS_NAVIGATION_MESSAGE_ODOMDRIVERFEEDBACK_H
#include <string>
#include <vector>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/message.h"
#include "ros/time.h"

#include "geometry_msgs/PoseStamped.h"

namespace higgs_navigation
{
template <class ContainerAllocator>
struct OdomDriverFeedback_ : public ros::Message
{
  typedef OdomDriverFeedback_<ContainerAllocator> Type;

  OdomDriverFeedback_()
  : base_position()
  {
  }

  OdomDriverFeedback_(const ContainerAllocator& _alloc)
  : base_position(_alloc)
  {
  }

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _base_position_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  base_position;


private:
  static const char* __s_getDataType_() { return "higgs_navigation/OdomDriverFeedback"; }
public:
  ROS_DEPRECATED static const std::string __s_getDataType() { return __s_getDataType_(); }

  ROS_DEPRECATED const std::string __getDataType() const { return __s_getDataType_(); }

private:
  static const char* __s_getMD5Sum_() { return "3fb824c456a757373a226f6d08071bf0"; }
public:
  ROS_DEPRECATED static const std::string __s_getMD5Sum() { return __s_getMD5Sum_(); }

  ROS_DEPRECATED const std::string __getMD5Sum() const { return __s_getMD5Sum_(); }

private:
  static const char* __s_getMessageDefinition_() { return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
geometry_msgs/PoseStamped base_position # result\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
"; }
public:
  ROS_DEPRECATED static const std::string __s_getMessageDefinition() { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED const std::string __getMessageDefinition() const { return __s_getMessageDefinition_(); }

  ROS_DEPRECATED virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    ros::serialization::OStream stream(write_ptr, 1000000000);
    ros::serialization::serialize(stream, base_position);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    ros::serialization::IStream stream(read_ptr, 1000000000);
    ros::serialization::deserialize(stream, base_position);
    return stream.getData();
  }

  ROS_DEPRECATED virtual uint32_t serializationLength() const
  {
    uint32_t size = 0;
    size += ros::serialization::serializationLength(base_position);
    return size;
  }

  typedef boost::shared_ptr< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct OdomDriverFeedback
typedef  ::higgs_navigation::OdomDriverFeedback_<std::allocator<void> > OdomDriverFeedback;

typedef boost::shared_ptr< ::higgs_navigation::OdomDriverFeedback> OdomDriverFeedbackPtr;
typedef boost::shared_ptr< ::higgs_navigation::OdomDriverFeedback const> OdomDriverFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace higgs_navigation

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator>
struct MD5Sum< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3fb824c456a757373a226f6d08071bf0";
  }

  static const char* value(const  ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3fb824c456a75737ULL;
  static const uint64_t static_value2 = 0x3a226f6d08071bf0ULL;
};

template<class ContainerAllocator>
struct DataType< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "higgs_navigation/OdomDriverFeedback";
  }

  static const char* value(const  ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
geometry_msgs/PoseStamped base_position # result\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.base_position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct OdomDriverFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::higgs_navigation::OdomDriverFeedback_<ContainerAllocator> & v) 
  {
    s << indent << "base_position: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.base_position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HIGGS_NAVIGATION_MESSAGE_ODOMDRIVERFEEDBACK_H

